### ISSUE TITLE
Hello,I'm dowmload lame V3.110(October 2017),build and find Undefined symbols for architecture arm64!

### ISSUE THREAD

**Issue by iMinger** [kewlbear/lame-ios-build#4]
Undefined symbols for architecture arm64:
  "_lame_init", referenced from:
      -[CXHRecordView transformCAFToMP3:] in CXHRecordView.o
  "_lame_encode_buffer_interleaved", referenced from:
      -[CXHRecordView transformCAFToMP3:] in CXHRecordView.o
  "_lame_set_VBR", referenced from:
      -[CXHRecordView transformCAFToMP3:] in CXHRecordView.o
  "_lame_init_params", referenced from:
      -[CXHRecordView transformCAFToMP3:] in CXHRecordView.o
  "_lame_set_in_samplerate", referenced from:
      -[CXHRecordView transformCAFToMP3:] in CXHRecordView.o
  "_lame_encode_flush", referenced from:
      -[CXHRecordView transformCAFToMP3:] in CXHRecordView.o
  "_lame_close", referenced from:
      -[CXHRecordView transformCAFToMP3:] in CXHRecordView.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by FrankSwift** [comment]
I hava some problem! Do u solve it?

**Comment by FrankSwift** [comment]
I hava same problem! Do u solve it?

**Comment by kewlbear** [comment]
Make sure you have specified correct path to `fat-lame/lib` in "Library Search Paths."

**Comment by iMinger** [comment]
got it!
